---
language: php
sudo: required
env:
  global:
    - TEST_S3_LOCATION='//TRAVISACCESSPHPUNIT:wJalrXUtnFEMI%2FSECRET%2FTRAVISPHPUNIT@us-east-1/?endpoint=http%3A%2F%2F127.0.0.1%3A9999&use_path_style_endpoint=1'
    - TEST_FTP_LOCATION='ftp://test:test@localhost'

services:
  - docker
  - redis-server
  - memcached

cache:
  bundler: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.ocular

jobs:
  include:
    - php: 7.4
      name: Linting
      stage: lint
      before_install:
        - npm set loglevel error
        - npm set progress false
      install:
        - sudo apt-get install libxml2-utils
        - npm install -g jsonlint
        - curl https://bootstrap.pypa.io/get-pip.py >> ~/get-pip.py
        - sudo python ~/get-pip.py
        - sudo pip install yamllint
      script:
        - >
          find . -type f -name "*.json" -not -path "./vendor/*" -print0 |
          xargs -0 --no-run-if-empty -n1 jsonlint -q ;
        - >
          find . -type f -name "*.yml" -not -path "./vendor/*" -print0 |
          xargs -0 --no-run-if-empty -n1 yamllint
        - >
          find . -type f -name "*.xml" -not -path "./vendor/*" -print0 |
          xargs -0 --no-run-if-empty -n1 xmllint --noout --encode utf-8
        - composer validate
      after_script:
        - echo Dummy after script
    - stage: test
      php: 7.4
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0
  allow_failures:
    - stage: test
      php: 8.0

before_install:
  - env
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - wget https://scrutinizer-ci.com/ocular.phar -O ~/.ocular/ocular.phar
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer global require jakub-onderka/php-parallel-lint jakub-onderka/php-console-highlighter sensiolabs/security-checker;
  - "docker run -p 9999:9999 --name minio --rm \
    -e 'MINIO_ACCESS_KEY=TRAVISACCESSPHPUNIT' \
    -e 'MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/TRAVISKEYPHPUNIT' \
    --detach minio/minio server /data"
  - "docker run -d -p 21:21 -p 30000-30009:30000-30009 -e 'PUBLICHOST=localhost' jack12816/ftpd_test"

script:
  - composer install --prefer-dist

  - "if [[ -e ~/.composer/vendor/bin/parallel-lint ]] ; then ~/.composer/vendor/bin/parallel-lint ./src ; fi"
  - "if [[ -e ./vendor/bin/phpcs ]] ; then ./vendor/bin/phpcs -i ; fi"
  - "if [[ -e ./vendor/bin/phpcs ]] ; then ./vendor/bin/phpcs -s -p -n ./src ; fi"
  - "if [[ -e ~/.composer/vendor/bin/security-checker ]] ; then ~/.composer/vendor/bin/security-checker -n security:check --end-point=http://security.symfony.com/check_lock; fi"
  - php -dxdebug.mode=coverage -dxdebug.coverage_enable=1 ./vendor/bin/phpunit

after_script:
  - >
    if [[ ${TRAVIS_PHP_VERSION} == "7.0" || ${TRAVIS_PHP_VERSION} == "7.4" ]] ; then
    php ~/.ocular/ocular.phar code-coverage:upload --format=php-clover coverage.xml -vvv ;
    fi
